name: Deploy Static Site Artifact

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Upload everything in the repo as a Pages artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./       # Upload root folder

      # 3. Deploy artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
