name: CI/CD for Fire CRM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Upload files for GitHub Pages deployment
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      # 3. Deploy to GitHub Pages
      - name: Deploy to Pages
        uses: actions/deploy-pages@v1

