name: Simple GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - uses: actions/checkout@v3

      # 2. Deploy to GitHub Pages using v4
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages       # Branch to deploy to
          folder: ./             # Folder to deploy (root of repo)
          clean: true            # Remove old files in gh-pages

