name: CI/CD for Fire CRM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup GitHub Pages deployment
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # 3. Upload files for deployment
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      # 4. Deploy to GitHub Pages
      - name: Deploy
        uses: actions/deploy-pages@v1
