name: GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Deploy using JamesIves v4
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages      # Branch to deploy to
          folder: ./            # Deploy root folder
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub Actions token
