name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - uses: actions/checkout@v3

      # 2. Upload files for Pages deployment (latest version)
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./        # Deploy all files in the root

      # 3. Deploy to GitHub Pages (latest supported)
      - uses: actions/deploy-pages@v1
