name: Simple GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./          # Root folder containing index.html
          publish_branch: gh-pages # Branch will be created automatically
          user_name: github-actions
          user_email: github-actions@users.noreply.github.com
